CREATE TABLE IF NOT EXISTS hhdata__agg_weekly_refresh_runs (
    id VARCHAR(128) PRIMARY KEY,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    mode VARCHAR(64) NOT NULL DEFAULT 'refresh',
    status VARCHAR(64) NOT NULL,
    source_row_count INT NOT NULL DEFAULT 0,
    metric_row_count INT NOT NULL DEFAULT 0,
    gap_count INT NOT NULL DEFAULT 0,
    mapping_row_count INT NOT NULL DEFAULT 0,
    message LONGTEXT,
    params JSON,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    finished_at DATETIME(6),
    KEY idx_hhdata_weekly_runs_week (week_start, week_end, created_at),
    KEY idx_hhdata_weekly_runs_status (status, created_at)
);

CREATE TABLE IF NOT EXISTS hhdata__agg_weekly_metrics (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    day_count INT NOT NULL,
    dimension_code VARCHAR(32) NOT NULL,
    dimension_name VARCHAR(32) NOT NULL,
    contact_person VARCHAR(512) NOT NULL,
    operator_name VARCHAR(128) NOT NULL,
    brand_name VARCHAR(128) NOT NULL,
    city_name VARCHAR(128) NOT NULL,
    mapping_status VARCHAR(32) NOT NULL,
    source_row_count INT NOT NULL DEFAULT 0,
    dimension_key_hash CHAR(64) NOT NULL,
    passenger_order_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    broadcast_orders DECIMAL(38,10) NOT NULL DEFAULT 0,
    match_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    response_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    completed_order_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    cancelled_before_answer DECIMAL(38,10) NOT NULL DEFAULT 0,
    cancelled_by_passenger DECIMAL(38,10) NOT NULL DEFAULT 0,
    cancelled_by_driver DECIMAL(38,10) NOT NULL DEFAULT 0,
    online_duration_hour DECIMAL(38,10) NOT NULL DEFAULT 0,
    online_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    completed_drivers DECIMAL(38,10) NOT NULL DEFAULT 0,
    peak_online_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    peak_valid_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    valid_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    approved_drivers DECIMAL(38,10) NOT NULL DEFAULT 0,
    first_online_drivers DECIMAL(38,10) NOT NULL DEFAULT 0,
    first_completion_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    gmv DECIMAL(38,10) NOT NULL DEFAULT 0,
    total_b_subsidy DECIMAL(38,10) NOT NULL DEFAULT 0,
    merchant_b_subsidy DECIMAL(38,10) NOT NULL DEFAULT 0,
    total_commission DECIMAL(38,10) NOT NULL DEFAULT 0,
    brand_commission DECIMAL(38,10) NOT NULL DEFAULT 0,
    card_merchant_income DECIMAL(38,10) NOT NULL DEFAULT 0,
    refresh_run_id VARCHAR(128) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_hhdata_weekly_metrics_dim_hash (week_start, dimension_key_hash),
    KEY idx_hhdata_weekly_metrics_week_dim (week_start, week_end, dimension_code),
    KEY idx_hhdata_weekly_metrics_brand_city (week_start, brand_name, city_name),
    KEY idx_hhdata_weekly_metrics_run (refresh_run_id)
);

CREATE TABLE IF NOT EXISTS hhdata__agg_weekly_gaps (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    refresh_run_id VARCHAR(128) NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    gap_type VARCHAR(64) NOT NULL,
    dimension_code VARCHAR(32),
    dimension_name VARCHAR(32),
    contact_person VARCHAR(512),
    operator_name VARCHAR(128),
    brand_name VARCHAR(128),
    city_name VARCHAR(128),
    field_name VARCHAR(128),
    period_name VARCHAR(32),
    reason LONGTEXT,
    payload JSON,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_hhdata_weekly_gaps_run (refresh_run_id),
    KEY idx_hhdata_weekly_gaps_week_type (week_start, week_end, gap_type),
    KEY idx_hhdata_weekly_gaps_brand_city (brand_name, city_name)
);

CREATE TABLE IF NOT EXISTS hhdata__agg_daily_brand_city_metrics (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_date DATE NOT NULL,
    brand_name VARCHAR(128) NOT NULL,
    city_name VARCHAR(128) NOT NULL,
    source_row_count INT NOT NULL DEFAULT 0,
    brand_city_key_hash CHAR(64) NOT NULL,
    passenger_order_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    broadcast_orders DECIMAL(38,10) NOT NULL DEFAULT 0,
    match_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    response_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    completed_order_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    cancelled_before_answer DECIMAL(38,10) NOT NULL DEFAULT 0,
    cancelled_by_passenger DECIMAL(38,10) NOT NULL DEFAULT 0,
    cancelled_by_driver DECIMAL(38,10) NOT NULL DEFAULT 0,
    online_duration_hour DECIMAL(38,10) NOT NULL DEFAULT 0,
    online_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    completed_drivers DECIMAL(38,10) NOT NULL DEFAULT 0,
    peak_online_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    peak_valid_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    valid_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    approved_drivers DECIMAL(38,10) NOT NULL DEFAULT 0,
    first_online_drivers DECIMAL(38,10) NOT NULL DEFAULT 0,
    first_completion_driver_count DECIMAL(38,10) NOT NULL DEFAULT 0,
    gmv DECIMAL(38,10) NOT NULL DEFAULT 0,
    total_b_subsidy DECIMAL(38,10) NOT NULL DEFAULT 0,
    merchant_b_subsidy DECIMAL(38,10) NOT NULL DEFAULT 0,
    total_commission DECIMAL(38,10) NOT NULL DEFAULT 0,
    brand_commission DECIMAL(38,10) NOT NULL DEFAULT 0,
    card_merchant_income DECIMAL(38,10) NOT NULL DEFAULT 0,
    refresh_run_id VARCHAR(128) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_hhdata_daily_brand_city_hash (metric_date, brand_city_key_hash),
    KEY idx_hhdata_daily_brand_city_date (metric_date),
    KEY idx_hhdata_daily_brand_city_names (brand_name, city_name),
    KEY idx_hhdata_daily_brand_city_run (refresh_run_id)
);
